version: '3'
services:

  engster_server:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: /bin/sh -c "scripts/start-dev.sh"
    ports:
      - 8000:8000
    env_file:
      - secrets/.env.development
    volumes:
      - ./:/app/
      - packages:/usr/local/lib/python3.7/site-packages/
      - python-bin:/usr/local/bin
    networks:
      - db_network
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - secrets/.env.development
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - db_network
    environment:
      - POSTGRES_DB=engster
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

networks:
  db_network:
    driver: bridge

volumes:
  db_volume:
  packages:
  python-bin: